### ISSUE TITLE
Can't deploy this project

### ISSUE THREAD

**Issue by wianoski** [caglarturali/caglarturali.github.io#1]
hey i wanna ask this problem to you, i want to deploy this project on github or netlify, or heroku, but how ? Thank you

**Comment by caglarturali** [comment]
Hey. Sorry about the late response. The project should be ready to go on GitHub as it currently stands. But other platforms might require a bit of tweaking since it uses a custom webpack configuration. I'm planning to rewrite this app with create-react-app, but seems like it won't happen anytime soon, unfortunately. Still, you can watch the repo and give another try when the new version is ready. Thanks. :blush:
